//<script type="text/javascript">
function writeHTMLasJS(){
document.write("<!doctype html>");
document.write("<html lang=\"en\" class=\"index-pg-bg\">");
document.write("<!-- <html lang=\"en\" class=\"container-body container-body-item\"> -->");
document.write("");
document.write("<!-- This is the WELCOME page  -->");
document.write("");
document.write("<head>");
document.write("");
document.write("    <!-- Required meta tags -->");
document.write("    <meta charset=\"utf-8\">");
document.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">");
document.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">");
document.write("");
document.write("    <!-- Bootstrap CSS -->");
document.write("    <link rel=\"stylesheet\" href=\"https:\/\/maxcdn.bootstrapcdn.com\/bootstrap\/4.0.0\/css\/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW\/dAiS6JXm\"");
document.write("        crossorigin=\"anonymous\">");
document.write("");
document.write("    <!-- Pulling Icons from fontawesome site -->");
document.write("    <script defer src=\"https:\/\/use.fontawesome.com\/releases\/v5.0.8\/js\/all.js\"><\/script>");
document.write("    <link rel=\"stylesheet\" href=\".\/CSS\/style.css\" \/>");
document.write("");
document.write("<\/head>");
document.write("");
document.write("<body>");
document.write("    <div class=\"container-header header-bar-name \">John Vornberger<\/div>");
document.write("");
document.write("    <!-- The \"sidebar\" id is used for the hamburger button which opens and closes the sidebar menu... -->");
document.write("    <div id=\"sidebar\">");
document.write("        <div class=\"toggle-btn\" id=\"nav-hover\" onclick=\"toggleSidebar()\">");
document.write("            <span><\/span>");
document.write("            <span><\/span>");
document.write("            <span><\/span>");
document.write("        <\/div>");
document.write("");
document.write("        <!-- The menu id is for the vertical menu -->");
document.write("        <!-- Using a container to separate the text from the icons -->");
document.write("");
document.write("        <ul id=\"menu\">");
document.write("            <li class=\"selected\">");
document.write("                <div id=\"container-menu flex-menu-l flex-menu-r\">");
document.write("                    <a id=\"container-menu\" class=\"flex-menu-l selected\" href=\"index.html\">Welcome <\/a>");
document.write("                    <i class=\"dead-icons flex-menu-r  fas fa-handshake fa-2x \"><\/i>");
document.write("                <\/div>");
document.write("");
document.write("            <\/li>");
document.write("            <li>");
document.write("                <div id=\"container-menu flex-menu-l flex-menu-r\">");
document.write("                    <a id=\"container-menu\" class=\"flex-menu-l\" href=\"about.html\">About <\/a>");
document.write("                    <i class=\"dead-icons flex-menu-r  fas fa-address-card fa-2x \"><\/i>");
document.write("                <\/div>");
document.write("            <\/li>");
document.write("            <li>");
document.write("                <div id=\"container-menu flex-menu-l flex-menu-r\">");
document.write("                    <a id=\"container-menu\" class=\"flex-menu-l\" href=\"experience.html\">Experience<\/a>");
document.write("                    <i class=\"dead-icons  fas fa-chart-line fa-2x \"><\/i>");
document.write("                <\/div>");
document.write("            <\/li>");
document.write("            <li>");
document.write("                <div id=\"container-menu flex-menu-l flex-menu-r\">");
document.write("                    <a id=\"container-menu\" class=\"flex-menu-l\" href=\"skills.html\">Skills<\/a>");
document.write("                    <i class=\"dead-icons flex-menu-r  fas fa-list-alt fa-2x\"><\/i>");
document.write("                <\/div>");
document.write("            <\/li>");
document.write("            <!-- <li>");
document.write("                <div id=\"container-menu flex-menu-l flex-menu-r\">");
document.write("                    <a id=\"container-menu\" class=\"flex-menu-l\" href=\"badges.html\">Badges<\/a>");
document.write("                    <i class=\"dead-icons flex-menu-r  fas fa-shield-alt fa-2x\"><\/i>");
document.write("                <\/div>");
document.write("            <\/li> -->");
document.write("            <li>");
document.write("                <div id=\"container-menu flex-menu-l flex-menu-r\">");
document.write("                    <a id=\"container-menu\" class=\"flex-menu-l\" href=\"education.html\">Education<\/a>");
document.write("                    <i class=\"dead-icons flex-menu-r  fas fa-graduation-cap fa-2x\"><\/i>");
document.write("                <\/div>");
document.write("            <\/li>");
document.write("            <li>");
document.write("                <div id=\"container-menu flex-menu-l flex-menu-r\">");
document.write("                    <a id=\"container-menu\" class=\"flex-menu-l\" href=\"contact.html\">Contact<\/a>");
document.write("                    <i class=\"dead-icons flex-menu-r  fas fa-at fa-2x\"><\/i>");
document.write("                <\/div>");
document.write("            <\/li>");
document.write("            <li>");
document.write("                <div id=\"container-menu flex-menu-l flex-menu-r\">");
document.write("                    <a id=\"container-menu\" class=\"flex-menu-l\" href=\"bitsbytes.html\">Bits &#38; Bytes<\/a>");
document.write("                    <i class=\"dead-icons flex-menu-r  fas fa-image fa-2x\"><\/i>");
document.write("                <\/div>");
document.write("            <\/li>");
document.write("            <li>");
document.write("                <div id=\"container-menu flex-menu-l flex-menu-r\">");
document.write("                    <a id=\"container-menu\" class=\"flex-menu-l\" href=\"https:\/\/drive.google.com\/file\/d\/1fWinZFEL51-ilQFaobIOl1Owxn78hzep\/view?usp=sharing\">Resume<\/a>");
document.write("                    <i class=\"dead-icons flex-menu-r fas fa-file-alt fa-2x\"><\/i>");
document.write("                <\/div>");
document.write("            <\/li>");
document.write("        <\/ul>");
document.write("    <\/div>");
document.write("");
document.write("");
document.write("    <main>");
document.write("    <\/main>");
document.write("");
document.write("    <footer>");
document.write("");
document.write("    <\/footer>");
document.write("    <!-- jQuery first, then Popper.js, then Bootstrap JS -->");
document.write("    <script src=\"https:\/\/code.jquery.com\/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr\/rE9\/Qpg6aAZGJwFDMVNA\/GpGFF93hXpG5KkN\"");
document.write("        crossorigin=\"anonymous\"><\/script>");
document.write("    <script src=\"https:\/\/cdnjs.cloudflare.com\/ajax\/libs\/popper.js\/1.12.9\/umd\/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K\/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\"");
document.write("        crossorigin=\"anonymous\"><\/script>");
document.write("    <script src=\"https:\/\/maxcdn.bootstrapcdn.com\/bootstrap\/4.0.0\/js\/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe\/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\"");
document.write("        crossorigin=\"anonymous\"><\/script>");
document.write("    <script defer src=\"https:\/\/use.fontawesome.com\/releases\/v5.0.6\/js\/all.js\"><\/script>");
document.write("    <script src=\".\/JS\/main.js\"><\/script>");
document.write("");
document.write("");
document.write("<\/body>");
document.write("");
document.write("<\/html>");
}

writeHTMLasJS();

